#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        print(AAAAAAAAAAAAAAAAAAAAAAA)
    except NameError as ne:
        print(message)
